---
namespace: ms
name: homeserver
version: 1.1.0
description: |
  Home server management collection for system information and configuration.
  Supports Ubuntu, Debian, openSUSE, RedHat/CentOS/Rocky, and Alpine Linux.

  Compatibility Matrix:
  - Ansible 2.15.x: Python 3.9+
  - Ansible 2.16.x: Python 3.10+
  - Ansible 2.17.x: Python 3.10+
readme: README.md
authors:
  - ms
license:
  - MIT
license_file: ''
tags:
  - system
  - info
  - homeserver
  - automation
  - infrastructure
  - python
  - monitoring
  - linux
  - ubuntu
  - debian
  - opensuse
  - redhat
  - alpine
dependencies:
  "ansible.posix": ">=1.0.0"
  "community.general": ">=3.0.0"
repository: https://github.com/codeopsms/ansible-collection-homeserver
documentation: https://github.com/codeopsms/ansible-collection-homeserver
homepage: https://github.com/codeopsms/ansible-collection-homeserver
issues: https://github.com/codeopsms/ansible-collection-homeserver/issues
build_ignore:
  - '*.tar.gz'
  - '.git'
  - '.gitignore'
  - 'tests/'
  - '*.pyc'
  - '__pycache__'
